rootProject.name = 'HackwarsClassic'

include ':HackWars'
project(':HackWars').projectDir = file('src/HackWars')
project(':HackWars').buildFileName = 'hackwars.gradle'

include ':RpcDispatchAnnotations'
project(':RpcDispatchAnnotations').projectDir = file('src/RpcDispatchAnnotations')
project(':RpcDispatchAnnotations').buildFileName = 'rpcDispatchAnnotations.gradle'

include ':RpcDispatchKsp'
project(':RpcDispatchKsp').projectDir = file('src/RpcDispatchKsp')
project(':RpcDispatchKsp').buildFileName = 'rpcDispatchKsp.gradle'

include ':GameServer'
project(':GameServer').projectDir = file('src/GameServer')
project(':GameServer').buildFileName = 'GameServer.gradle'

include ':Client'
project(':Client').projectDir = file('src/Client')
project(':Client').buildFileName = 'client.gradle'

include ':Networking'
project(':Networking').projectDir = file('src/Networking')
project(':Networking').buildFileName = 'networking.gradle'

include ':ChatServer'
project(':ChatServer').projectDir = file('src/ChatServer')
project(':ChatServer').buildFileName = 'chatServer.gradle'

include ':Data'
project(':Data').projectDir = file('src/Data')
project(':Data').buildFileName = 'data.gradle'

include ':Integration'
project(':Integration').projectDir = file('src/Integration')
project(':Integration').buildFileName = 'integration.gradle'

include ':RewriteBuildLogic'
project(':RewriteBuildLogic').projectDir = file('src/RewriteBuildLogic')

include ':RewriteProtocol'
project(':RewriteProtocol').projectDir = file('src/RewriteProtocol')

include ':RewriteGameCore'
project(':RewriteGameCore').projectDir = file('src/RewriteGameCore')

include ':RewriteChatCore'
project(':RewriteChatCore').projectDir = file('src/RewriteChatCore')

include ':RewritePersistence'
project(':RewritePersistence').projectDir = file('src/RewritePersistence')

include ':RewriteClientModel'
project(':RewriteClientModel').projectDir = file('src/RewriteClientModel')

include ':RewriteHackScript'
project(':RewriteHackScript').projectDir = file('src/RewriteHackScript')

include ':RewriteTestKit'
project(':RewriteTestKit').projectDir = file('src/RewriteTestKit')

include ':RewriteGameServer'
project(':RewriteGameServer').projectDir = file('src/RewriteGameServer')

include ':RewriteChatServer'
project(':RewriteChatServer').projectDir = file('src/RewriteChatServer')

include ':RewriteClient'
project(':RewriteClient').projectDir = file('src/RewriteClient')
