package game.computer.runtime

import game.Port

fun baseRuntimeState(now: Long = 1_000L): RuntimeTickState {
    return RuntimeTickState(
        now = now,
        ip = "5.5.5.5",
        loaded = true,
        loading = false,
        loggedIn = true,
        loadFailure = false,
        logoutRequested = false,
        countDown = false,
        countDownStart = 0,
        countDownLengthMs = 1_000L,
        lastAccessed = 0,
        computerTimeoutMs = 10_000L,
        lastSave = 0,
        autoSaveMs = 1_000L,
        loadRequester = "",
        errorMessage = "load failed",
        pendingTasks = mutableListOf(),
        lastPingTime = 0,
        logInTime = 100L,
        lastClientPacketTime = 0,
        pingTimeoutMs = 1_000L,
        clientPacketTimeoutMs = 1_000L,
        lastPaid = 0,
        payPeriodMs = 10_000L,
        dailyPaySize = 1_000f,
        dailyPayReduction = 1f,
        inactive = false,
        npc = false,
        type = 0,
        httpActive = true,
        httpLevel = 3f,
        pettyCash = 0f,
        bankMoney = 0f,
        myVotes = 0,
        adRevenueTarget = "7.7.7.7",
        currentCPU = 0f,
        reportCPU = 0f,
        baseCPU = 0f,
        currentWatchCost = 0f,
        cpuLoadCalculated = false,
        lastAttack = 0,
        attackRateMs = 1_000L,
        healCounter = 0,
        healMod = 1,
        overheatStart = -1,
        overHeatTimeMs = 1_000L,
        sentOverHeatedMessage = false,
        cpuMaximum = 100f,
        lockCount = 0,
        locked = false,
        resendCaptcha = false,
        captchaThreshold = 5,
        unlockKey = "",
        operationCount = 0,
        grantFilesInterval = 3,
        grantFilesCounter = 0,
        captchaGenerator = { RuntimeCaptchaPayload("12345", intArrayOf(1, 2, 3)) },
        watchCostSupplier = { 5f }
    )
}

fun runtimePort(
    number: Int,
    type: Int = Port.ATTACK,
    on: Boolean = true,
    attacking: Boolean = false,
    overHeated: Boolean = false,
    health: Float = 100f,
    cpuCost: Float = 0f,
    baseCpuCostTotal: Float = 0f,
    lastDamageWindowHandle: Int = 0,
    accessing: String = "",
    targetPort: Int = -1,
    targetIp: String = "",
    maliciousTarget: String = "",
    isZombie: Boolean = false
): RuntimePortSnapshot {
    return RuntimePortSnapshot(
        number = number,
        type = type,
        on = on,
        attacking = attacking,
        overHeated = overHeated,
        health = health,
        cpuCost = cpuCost,
        baseCpuCostTotal = baseCpuCostTotal,
        lastDamageWindowHandle = lastDamageWindowHandle,
        accessing = accessing,
        targetPort = targetPort,
        targetIp = targetIp,
        maliciousTarget = maliciousTarget,
        isZombie = isZombie
    )
}
