apply from: "${rootDir}/src/RewriteBuildLogic/gradle/rewrite-application.gradle"

description = 'Rewrite game server application.'

application {
    mainClass = 'com.hackwars.rewrite.gameserver.RewriteGameServerKt'
}

dependencies {
    implementation project(':RewriteProtocol')
    implementation project(':RewriteGameCore')
    implementation project(':RewriteHackScript')
    implementation project(':RewritePersistence')
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.1"

    testImplementation project(':RewriteTestKit')
}
