hackerRPC=HackerLogin.HackerRPC
loginrpc=Legacy.LegacyPhpXmlRpc
checkdate=Legacy.LegacyPhpXmlRpc
domain=Legacy.LegacyPhpXmlRpc
bookmarks=Legacy.LegacyPhpXmlRpc
settings=Legacy.LegacyPhpXmlRpc
functions=Legacy.LegacyPhpXmlRpc
tutorials=Legacy.LegacyPhpXmlRpc
sounds=Legacy.LegacyPhpXmlRpc
profile=Legacy.LegacyPhpXmlRpc
facebook=Legacy.LegacyPhpXmlRpc
mail=Legacy.LegacyPhpXmlRpc
