rm Game/*.class
rm Server/*.class
rm Game/ComputerFunctions/*.class
rm Game/MMO/*.class
rm Game/RunChallenge/*.class
rm Assignments/*.class
rm Client/*.class
rm Browser/*.class
rm chat/messages/*.class
rm chat/util/*.class
rm chat/client/*.class
rm chatServer/Assignments/*.class
rm chatServer/chat/messages/*.class
rm chatServer/chat/server/*.class
rm chatServer/chat/util/*.class
rm chatServer/com/plink/dolphinnet/*.class
rm chatServer/Server/*.class
rm chatServer/util/*.class
rm com/plink/dolphinnet/*.class
rm com/plink/dolphinnet/util/*.class
rm com/plink/dolphinnet/assignments/*.class
rm com/plink/Hack3D/*.class
rm DBAdmin/*.class
rm GUI/*.class
rm HackerLogin/*.class
rm HackerSearch/Assignments/*.class
rm HackerSearch/Server/*.class
rm HackerSearch/util/*.class
rm Hackscript/*.class
rm Hackscript/Model/*.class
rm Hacktendo/*.class
rm Hacktendo/Functions/*.class
rm View/*.class
rm util/*.class
rm com/plink/dolphinstem/*.class
rm com/plink/dolphinstem/util/*.class
